excessive-nesting-threshold = 4
too-many-lines-threshold = 60
too-many-arguments-threshold = 5

allow-unwrap-in-tests = true
allow-expect-in-tests = true
allow-unwrap-in-consts = true
allow-expect-in-consts = true
allow-useless-vec-in-tests = true
