[forest]
name = "bottlerocket"

[[member]]
name = "bottlerocket"
remote = "git@github.com:bottlerocket-os/bottlerocket.git"
path = "bottlerocket"
default_branch = "develop"

[[member]]
name = "core-kit"
remote = "git@github.com:bottlerocket-os/bottlerocket-core-kit.git"
path = "kits/bottlerocket-core-kit"
default_branch = "develop"

[[member]]
name = "kernel-kit"
remote = "git@github.com:bottlerocket-os/bottlerocket-kernel-kit.git"
path = "kits/bottlerocket-kernel-kit"
default_branch = "develop"

[[member]]
name = "twoliter"
remote = "git@github.com:bottlerocket-os/twoliter.git"
path = "twoliter"
default_branch = "develop"

[[member]]
name = "sdk"
remote = "git@github.com:bottlerocket-os/bottlerocket-sdk.git"
path = "sdk/bottlerocket-sdk"
default_branch = "develop"

[[member]]
name = "admin-container"
remote = "git@github.com:bottlerocket-os/bottlerocket-admin-container.git"
path = "host-containers/bottlerocket-admin-container"
default_branch = "develop"

[[member]]
name = "control-container"
remote = "git@github.com:bottlerocket-os/bottlerocket-control-container.git"
path = "host-containers/bottlerocket-control-container"
default_branch = "develop"

[[member]]
name = "settings-sdk"
remote = "git@github.com:bottlerocket-os/bottlerocket-settings-sdk.git"
path = "bottlerocket-settings-sdk"
default_branch = "develop"
