//! Twoliter configuration management commands.
//!
//! Provides subcommands for switching between local and upstream kit sources:
//! * `use-local` - Configure current directory to use grove's local registry (both files)
//! * `use-local-deps` - Create only Twoliter.override for fetching dependencies
//! * `use-local-publish` - Create only Infra.toml for publishing
//! * `use-upstream` - Remove all local registry configuration
//! * `use-upstream-deps` - Remove only Twoliter.override
//! * `use-upstream-publish` - Remove only Infra.toml

use crate::grove::{GroveContext, GroveRegistryConfig};
use clap::{Parser, Subcommand};
use snafu::{ResultExt, Snafu};
use std::fs;
use std::path::Path;

use super::theme;

/// Manage Twoliter configuration
#[derive(Parser)]
pub struct TwoliterCommand {
    #[command(subcommand)]
    subcommand: TwoliterSubcommand,
}

#[allow(clippy::enum_variant_names)]
#[derive(Subcommand)]
enum TwoliterSubcommand {
    /// Configure to use local registry for kits (both deps and publish)
    UseLocal,
    /// Configure to use local registry for fetching dependencies only
    UseLocalDeps,
    /// Configure to use local registry for publishing only
    UseLocalPublish,
    /// Remove all local registry configuration
    UseUpstream,
    /// Remove local registry configuration for dependencies only
    UseUpstreamDeps,
    /// Remove local registry configuration for publishing only
    UseUpstreamPublish,
}

pub fn run(cmd: TwoliterCommand) -> Result<(), TwoliterError> {
    use twoliter_error::*;

    let grove = GroveContext::detect().context(GroveSnafu)?;
    let config = GroveRegistryConfig::for_grove(&grove).context(RegistryConfigSnafu)?;
    let port = config.port().into_inner();

    match cmd.subcommand {
        TwoliterSubcommand::UseLocal => {
            create_override(port)?;
            create_infra(port)?;
            Ok(())
        }
        TwoliterSubcommand::UseLocalDeps => create_override(port),
        TwoliterSubcommand::UseLocalPublish => create_infra(port),
        TwoliterSubcommand::UseUpstream => {
            let r1 = remove_override();
            let r2 = remove_infra();
            if !r1 && !r2 {
                println!("{}", theme::muted("No local configuration files found"));
            }
            Ok(())
        }
        TwoliterSubcommand::UseUpstreamDeps => {
            if !remove_override() {
                println!("{}", theme::muted("Twoliter.override not found"));
            }
            Ok(())
        }
        TwoliterSubcommand::UseUpstreamPublish => {
            if !remove_infra() {
                println!("{}", theme::muted("Infra.toml not found"));
            }
            Ok(())
        }
    }
}

fn create_override(port: u16) -> Result<(), TwoliterError> {
    use twoliter_error::*;
    let content = format!(
        "# Generated by brdev - do not edit\n# Run `brdev twoliter use-upstream` to remove\n\n[local]\nregistry = \"localhost:{}\"\n",
        port
    );
    fs::write("Twoliter.override", &content).context(WriteFileSnafu {
        path: "Twoliter.override",
    })?;
    println!("{} Created Twoliter.override", theme::success("✓"));
    println!(
        "  Local registry: {}",
        theme::url(format!("localhost:{}", port))
    );
    Ok(())
}

fn create_infra(port: u16) -> Result<(), TwoliterError> {
    use twoliter_error::*;
    let content = format!(
        "# Generated by brdev - do not edit\n# Run `brdev twoliter use-upstream` to remove\n\n[vendor.local]\nregistry = \"localhost:{}\"\n",
        port
    );
    fs::write("Infra.toml", &content).context(WriteFileSnafu { path: "Infra.toml" })?;
    println!("{} Created Infra.toml", theme::success("✓"));
    println!(
        "  Local registry: {}",
        theme::url(format!("localhost:{}", port))
    );
    Ok(())
}

fn remove_override() -> bool {
    if Path::new("Twoliter.override").exists() && fs::remove_file("Twoliter.override").is_ok() {
        println!("{} Removed Twoliter.override", theme::success("✓"));
        return true;
    }
    false
}

fn remove_infra() -> bool {
    if Path::new("Infra.toml").exists() && fs::remove_file("Infra.toml").is_ok() {
        println!("{} Removed Infra.toml", theme::success("✓"));
        return true;
    }
    false
}

use crate::grove::{GroveContextError, GroveRegistryConfigError};

#[derive(Debug, Snafu, miette::Diagnostic)]
#[snafu(module)]
pub enum TwoliterError {
    #[snafu(display("Not in a grove"))]
    #[diagnostic(
        code(brdev::twoliter::not_in_grove),
        help("Run this command from within a grove directory")
    )]
    Grove { source: GroveContextError },

    #[snafu(display("Failed to load registry configuration"))]
    #[diagnostic(
        code(brdev::twoliter::config_failed),
        help("Check grove registry configuration")
    )]
    RegistryConfig { source: GroveRegistryConfigError },

    #[snafu(display("Failed to write {}", path))]
    #[diagnostic(code(brdev::twoliter::write_failed))]
    WriteFile {
        path: &'static str,
        source: std::io::Error,
    },

    #[snafu(display("Failed to remove {}", path))]
    #[diagnostic(code(brdev::twoliter::remove_failed))]
    RemoveFile {
        path: &'static str,
        source: std::io::Error,
    },
}
