//! Forest worktree management.

use crate::error::Error;
use crate::forest::{ForestConfig, Member};
use std::path::PathBuf;
use std::process::Command;
use tracing::instrument;

/// Manages forest operations including seeding and worktrees.
#[derive(Debug)]
pub struct ForestManager {
    root: PathBuf,
    config: ForestConfig,
}

impl ForestManager {
    pub fn new(root: PathBuf, config: ForestConfig) -> Self {
        Self { root, config }
    }

    /// Path to bare repos storage.
    fn bare_dir(&self) -> PathBuf {
        self.root.join(".forest").join("bare")
    }

    /// Path to worktrees directory.
    fn worktrees_dir(&self) -> PathBuf {
        self.root.join("worktrees")
    }

    /// Seed the forest - clone bare repos and create develop worktree.
    #[instrument(err)]
    pub fn seed(&self, verbose: bool) -> Result<(), Error> {
        let bare_dir = self.bare_dir();
        std::fs::create_dir_all(&bare_dir).map_err(|e| Error::CreateDir {
            path: bare_dir.clone(),
            source: e,
        })?;

        // Clone all bare repos first
        for member in &self.config.forest.member {
            self.clone_bare(member, verbose)?;
        }

        // Ensure crumbly.toml exists, generate if needed
        self.ensure_crumbly_config(verbose)?;

        // Create the default "develop" worktree
        self.create_worktree("develop", None, verbose)?;

        Ok(())
    }

    /// Clone a member repo as bare.
    #[instrument(err)]
    fn clone_bare(&self, member: &Member, verbose: bool) -> Result<(), Error> {
        let bare_path = self.bare_dir().join(format!("{}.git", member.name));

        if !bare_path.exists() {
            if verbose {
                println!("Cloning {} (bare)...", member.name);
            }
            let status = Command::new("git")
                .args(["clone", "--bare", &member.remote])
                .arg(&bare_path)
                .status()
                .map_err(|_| Error::Git {
                    message: format!("Failed to clone {}", member.remote),
                })?;
            if !status.success() {
                return Err(Error::Git {
                    message: format!("git clone failed for {}", member.name),
                });
            }
        } else if verbose {
            println!("✓ {} bare repo exists", member.name);
        }

        Ok(())
    }
    /// Ensure crumbly.toml exists, generating it if needed or warning about missing members.
    fn ensure_crumbly_config(&self, verbose: bool) -> Result<(), Error> {
        use owo_colors::OwoColorize;

        let crumbly_path = self.root.join("crumbly.toml");
        let member_paths: Vec<String> = self
            .config
            .forest
            .member
            .iter()
            .map(|m| m.path.display().to_string())
            .collect();

        if !crumbly_path.exists() {
            // Generate initial crumbly.toml
            let config = Self::generate_crumbly_config(&member_paths);
            std::fs::write(&crumbly_path, config).map_err(|e| Error::CreateDir {
                path: crumbly_path.clone(),
                source: e,
            })?;
            if verbose {
                println!(
                    "{} Generated crumbly.toml with {} targets",
                    "✓".green(),
                    member_paths.len()
                );
            }
        } else {
            // Check for missing members
            let content = std::fs::read_to_string(&crumbly_path).unwrap_or_default();
            let missing: Vec<_> = member_paths
                .iter()
                .filter(|p| !content.contains(p.as_str()))
                .collect();
            if !missing.is_empty() {
                println!(
                    "{} Some members not in crumbly.toml targets: {}",
                    "!".yellow(),
                    missing
                        .iter()
                        .map(|s| s.as_str())
                        .collect::<Vec<_>>()
                        .join(", ")
                );
            }
        }
        Ok(())
    }

    /// Generate a crumbly.toml config with member paths as targets.
    fn generate_crumbly_config(member_paths: &[String]) -> String {
        let targets: Vec<String> = member_paths
            .iter()
            .map(|p| format!("    \"{}\"", p))
            .collect();
        format!(
            r#"# Sembly configuration for this forest
# Generated by forester seed

# Directories to index (your forest members)
targets = [
{},
]

# Uncomment to customize file types (default: markdown, rust)
# enabled-file-types = ["markdown", "rust"]

# Uncomment to configure Rust indexing
# [file-types.rust]
# visibility = ["public"]  # Options: public, crate, private
# items = ["all"]  # Options: all, modules, functions, structs, enums, traits, impls, type-aliases, constants
# min-doc-lines = 0

# Uncomment to add boost rules for search ranking
# [[boost-rules]]
# description = "Prioritize documentation"
# pattern = "**/docs/**"
# multiplier = 1.2
"#,
            targets.join(",\n")
        )
    }

    /// Create a new forest worktree.
    #[instrument(err)]
    pub fn create_worktree(
        &self,
        name: &str,
        branch: Option<&str>,
        verbose: bool,
    ) -> Result<(), Error> {
        let wt_dir = self.worktrees_dir().join(name);
        if wt_dir.exists() {
            if verbose {
                println!("✓ worktree '{}' already exists", name);
            }
            return Ok(());
        }

        std::fs::create_dir_all(&wt_dir).map_err(|e| Error::CreateDir {
            path: wt_dir.clone(),
            source: e,
        })?;

        for member in &self.config.forest.member {
            let bare_path = self.bare_dir().join(format!("{}.git", member.name));
            let member_wt_path = wt_dir.join(&member.path);

            // Ensure parent exists
            if let Some(parent) = member_wt_path.parent() {
                std::fs::create_dir_all(parent).map_err(|e| Error::CreateDir {
                    path: parent.to_path_buf(),
                    source: e,
                })?;
            }

            if verbose {
                println!("Creating worktree for {} in {}...", member.name, name);
            }

            // Determine branch: explicit > member default
            let target_branch = branch.unwrap_or_else(|| member.branch());

            // For non-develop worktrees, create a unique branch to avoid conflicts
            let use_new_branch = name != "develop" && branch.is_none();
            let new_branch_name = if use_new_branch {
                format!("{}/{}", name, member.name)
            } else {
                target_branch.to_string()
            };

            // Create worktree with appropriate branch strategy
            let status = if use_new_branch {
                // Create new branch from default branch
                Command::new("git")
                    .args(["worktree", "add", "-b", &new_branch_name])
                    .arg(&member_wt_path)
                    .arg(member.branch())
                    .current_dir(&bare_path)
                    .status()
                    .map_err(|_| Error::Git {
                        message: format!("Failed to create worktree for {}", member.name),
                    })?
            } else {
                // Try to checkout existing branch
                let status = Command::new("git")
                    .args(["worktree", "add"])
                    .arg(&member_wt_path)
                    .arg(target_branch)
                    .current_dir(&bare_path)
                    .status()
                    .map_err(|_| Error::Git {
                        message: format!("Failed to create worktree for {}", member.name),
                    })?;

                if !status.success() {
                    // If branch doesn't exist, create it from default
                    Command::new("git")
                        .args(["worktree", "add", "-b", target_branch])
                        .arg(&member_wt_path)
                        .arg(member.branch())
                        .current_dir(&bare_path)
                        .status()
                        .map_err(|_| Error::Git {
                            message: format!("Failed to create worktree for {}", member.name),
                        })?
                } else {
                    status
                }
            };

            if !status.success() {
                return Err(Error::Git {
                    message: format!("git worktree add failed for {}", member.name),
                });
            }

            Command::new("git")
                .args(["remote", "remove", "origin"])
                .current_dir(&member_wt_path)
                .status()
                .map_err(|_| Error::Git {
                    message: format!("Failed to remove origin remote for {}", member.name),
                })?;
        }

        // Create configured symlinks
        if let Some(wt_config) = &self.config.worktree {
            for symlink in &wt_config.symlink {
                let source = self.root.join(&symlink.source);
                let target = wt_dir.join(&symlink.target);
                if let Some(parent) = target.parent() {
                    std::fs::create_dir_all(parent).map_err(|e| Error::CreateDir {
                        path: parent.to_path_buf(),
                        source: e,
                    })?;
                }
                std::os::unix::fs::symlink(&source, &target).map_err(|e| Error::Symlink {
                    src: source.clone(),
                    tgt: target.clone(),
                    source: e,
                })?;
                if verbose {
                    println!(
                        "Created symlink: {} -> {}",
                        target.display(),
                        source.display()
                    );
                }
            }
        }

        // Update shared crumbly index with this worktree's context
        if verbose {
            println!("Updating crumbly index for {}...", name);
        }
        let context_path = format!("worktrees/{}", name);
        let _ = Command::new("crumbly")
            .args(["update", "--context", &context_path])
            .current_dir(&self.root)
            .status();

        if verbose {
            println!("✓ Created worktree '{}'", name);
        }

        Ok(())
    }

    /// List existing forest worktrees.
    #[instrument(err)]
    pub fn list_worktrees(&self) -> Result<Vec<String>, Error> {
        let wt_dir = self.worktrees_dir();
        if !wt_dir.exists() {
            return Ok(vec![]);
        }

        let mut worktrees = Vec::new();
        let entries = std::fs::read_dir(&wt_dir).map_err(|e| Error::CreateDir {
            path: wt_dir.clone(),
            source: e,
        })?;

        for entry in entries.flatten() {
            if entry.path().is_dir()
                && let Some(name) = entry.file_name().to_str()
            {
                worktrees.push(name.to_string());
            }
        }

        Ok(worktrees)
    }

    /// Remove a forest worktree.
    #[instrument(err)]
    pub fn remove_worktree(&self, name: &str, force: bool) -> Result<(), Error> {
        let wt_dir = self.worktrees_dir().join(name);
        if !wt_dir.exists() {
            return Err(Error::WorktreeNotFound {
                name: name.to_string(),
            });
        }

        // Remove git worktrees for each member
        for member in &self.config.forest.member {
            let bare_path = self.bare_dir().join(format!("{}.git", member.name));
            let member_wt_path = wt_dir.join(&member.path);

            let mut cmd = Command::new("git");
            cmd.args(["worktree", "remove"]);
            if force {
                cmd.arg("--force");
            }
            cmd.arg(&member_wt_path);
            cmd.current_dir(&bare_path);

            let _ = cmd.status(); // Ignore errors, directory might already be gone
        }

        // Remove the worktree directory
        let _ = std::fs::remove_dir_all(&wt_dir);

        Ok(())
    }
}
